# Generated by Django 4.2.7 on 2024-01-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0002_alter_data_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='revenue',
            field=models.FloatField(),
        ),
    ]
