version: '3.8'

services:
  api:
    container_name: data_analytics_api
    volumes:
      - .:/app
    # env_file:
    #   - ./api/.env
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    
    
volumes:
  postgres_data:
